### ISSUE TITLE
Docker Image Installation

### ISSUE THREAD

**Issue by anwarbashir** [AllAboutCode/EduBlocks#89]
There is a Docker File but no docker-compose.yml file. Can I install edublocks as a docker image?

**Comment by Code-Tap** [comment]
> docker-compose.yml

```
version: 3
services:
  edublock:
    build: .
    ports:
        - "8081:8081"
```

Just add this to the root dir of this project and run it
